import { useEffect } from 'react'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { getShops } from '@/services/users.service'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  useEffect(() => {
    const loadShop = async () => {
      await getShops()
    }
    // Call the function
    loadShop();
  }, []);
  return (
    <>
      <Head>
        <title>Planigo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        La meilleure app de réservation
      </main>
    </>
  )
}
